### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by AbleLincoln** [mightyselphie/prj-rev-bwfs-dasmoto#6]
Meets expectations

Great work on this project. I can tell you spent a lot of time on the code. It is very efficiently written and clean. I especially like how you are taking advantage of classes in your CSS.

The only issue I saw was your misuse of IDs. An ID should be used to mark a _unique_ element that doesn't appear anywhere else on the page. If you want to mark multiple elements that share properties you should be using a class. See my comment on this.

As an added challenge, try tweaking the styles a bit. I see you've started to explore with the font of the header. Try playing with more of the styles on the page and see what cool things you can come up with. Web development is as much an art as it is engineering. Have fun with it!

**Comment by mightyselphie** [comment]
THanks for the code review & feedback @AbleLincoln, much appreciated.
